Updates deploy script to use AWS

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,5 +1,31 @@
 #!/bin/bash
 
-echo "Deploying application to Heroku..."
-heroku container:login
-heroku container:push worker
+REGION=us-east-1
+ENV=$1
+
+if [ -z "$ENV" ]; then
+  echo "Environment argument missing"
+  exit 1
+fi
+
+TARGET_IMAGE=788332838494.dkr.ecr.$REGION.amazonaws.com/mrs-silence-dogood:latest
+SOURCE_IMAGE=mrs-silence-dogood:latest
+
+# Login to AWS EC2 Container Registry
+$(aws ecr get-login --no-include-email)
+
+echo "Stopping service task..."
+# This creates downtime
+aws ecs update-service --cluster $ENV --service mrs-silence-dogood --desired-count 0
+
+echo "Building image..."
+docker build -t $SOURCE_IMAGE .
+docker tag $SOURCE_IMAGE $TARGET_IMAGE
+
+echo "Pushing image..."
+docker push $TARGET_IMAGE
+
+echo "Updating service..."
+aws ecs update-service --cluster $ENV --service mrs-silence-dogood --desired-count 1
+
+echo "Deployment successful"
